### ISSUE TITLE
latest release

### ISSUE THREAD

**Issue by mand35** [smart-data-lake/sdl-visualization#11]
As a user I want to download always the latest version. Especially as a maintainer of another product using this tool, I do not want to be forced to re-specify the version all the time. 
Please define the latest release as this. Further the link to the asset should be version independent:
`https://github.com/smart-data-lake/sdl-visualization/releases/download/0.9.2/sdl-visualizer-0.9.2.zip` -> `https://github.com/smart-data-lake/sdl-visualization/releases/download/latest/sdl-visualizer-latest.zip`

**Comment by zzeekk** [comment]
Download artifacts from release/download/latest works if release is not marked as pre-release.
For the artifact name the recommendation is to not include the version number, see also https://gist.github.com/steinwaywhw/a4cd19cda655b8249d908261a62687f8?permalink_comment_id=4206170#gistcomment-4206170

**Comment by iliassoto** [comment]
Issue has been fixed by @zzeekk and will be merged into next release.
