### ISSUE TITLE
Improve Action and DataObject configuration site layout

### ISSUE THREAD

**Issue by zzeekk** [smart-data-lake/sdl-visualization#17]
DataObjects:
- Top should include more condensed
  - Type
  - Name (not id, if existing)
  - Path (if existing)
  - Db.Table, partitions, primary keys (if existing)
  - Tags displayed as MUI chips (https://mui.com/material-ui/react-chip/)
  - Layer and SubjectArea (if existing)
  - Extra: Written/Used by Action as links
- Foreign Keys as table in a foldable section (if existing)
- Constraints and Expectations as table in two foldable sections
- Additional properties as table in a foldable section
- Whole Hocon Code in a foldable section

Actions:
- Top should include more condensed
  - Type
  - Name (not id, if existing)
  - InputIds, OutputIds as links
  - Feed
  - Tags displayed as MUI chips (https://mui.com/material-ui/react-chip/)
- Transformations as table in a foldable section
- ExecutionMode/Condition
- Additional properties as table in a foldable section
- Whole Hocon Code in a foldable section

**Comment by iliassoto** [comment]
As of 30.09.22 --> Everything but HOCON code viz implemented.
