### ISSUE TITLE
description and markdown

### ISSUE THREAD

**Issue by mand35** [smart-data-lake/sdl-visualization#20]
As a user I can specify description in the hocon metadata section of an object AND/OR in a markdown file. 
In general, we can expect to have a more detailed view in the Markdown file. But we may expect to have both versions available. 

We may want to regard the metadata->description as *short description* and the Markdown file as (full) *description* and show both (if present) in the SDLB Viewer.

**Comment by iliassoto** [comment]
Combined both into one display and will merge into the next release. Please look at pull request.
