### ISSUE TITLE
Small Improvements for Lineage Graph Selected Edge

### ISSUE THREAD

**Issue by HX-Tfd** [smart-data-lake/sdl-visualization#88]
Small improvements that can be done depending on the necessity:

1. Highlight the source and destination nodes of the selected edge as well
2. Add pop-up window indicating the source and destination nodes when hovering on an edge
3. Add window (e.g. top left) to display minimal properties of the source and destination nodes of an edge that has been selected. Make source and destination names clickable to jump to object or show object details only

**Comment by zzeekk** [comment]
selecting edge and highlighting source/destination is enough for now.
